# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
# pipeline: list of functions to preprocess the text 
#   before passing through the rasa machine learning model
language: en
pipeline: 

- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "sentiment.SentimentAnalyzer"
- name: "namedEntity.NamedEntityRecognizer"
- name: "SklearnIntentClassifier" 

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: EmbeddingPolicy
